return {
--   "epwalsh/obsidian.nvim",
--   version = "*", -- recommended, use latest release instead of latest commit
--   lazy = false,
--   -- ft = "markdown",
--   dependencies = {
--     "nvim-lua/plenary.nvim",
--   },
--   opts = {
--     workspaces = {
--       {
--         name = "Notes", -- Name of the workspace
--         path = "/home/allannara/Documentos/Vault/03-RAW_NOTES/", -- Path to the notes directory
--       },
--     },
--     completition = {
--       nvim_cmp = true,
--     },
--     picker = {
--       -- Set your preferred picker. Can be one of 'telescope.nvim', 'fzf-lua', 'mini.pick' or 'snacks.pick'.
--       name = "telescope.pick",
--     },
--     mappings = {
--       -- Overrides the 'gf' mapping to work on markdown/wiki links within your vault.
--       ["gf"] = {
--         action = function()
--           return require("obsidian").util.gf_passthrough()
--         end,
--         opts = { noremap = false, expr = true, buffer = true },
--       },
--       -- Toggle check-boxes.
--       ["<leader>ch"] = {
--         action = function()
--           return require("obsidian").util.toggle_checkbox()
--         end,
--         opts = { buffer = true },
--       },
--       -- Smart action depending on context: follow link, show notes with tag, toggle checkbox, or toggle heading fold
--       ["<cr>"] = {
--         action = function()
--           return require("obsidian").util.smart_action()
--         end,
--         opts = { buffer = true, expr = true },
--       },
--     },
--
--     -- Settings for templates
--     templates = {
--       subdir = "99-TEMPLATES", -- Subdirectory for templates
--       date_format = "%Y-%m-%d-%a", -- Date format for templates
--       gtime_format = "%H:%M", -- Time format for templates
--       tags = "", -- Default tags for templates
--     },
--   },
}
